name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          set -e
          cd /var/www/portal
          echo "Deploying application ..."
          (php artisan down) || true
            git fetch origin master
            git reset --hard origin/master
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            yarn install --prod
            yarn run production
            php artisan optimize
          php artisan up
          echo "Application deployed!"
