name: Deploy

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: /usr/bin/php7.4 /usr/local/bin/composer install
    - name: Create .env file
      run: cp .env.example .env
    - name: Generate application key
      run: /usr/bin/php7.4 artisan key:generate
    - name: Run tests
      run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          set -e
          cd /var/www/portal
          echo "Deploying application ..."
          (php artisan down --message 'The app is being (quickly!) updated. Please try again in a minute.') || true
            git fetch origin master
            git reset --hard origin/master
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            yarn install --prod
            yarn run prod
            php artisan optimize
          php artisan up
          echo "Application deployed!"
